server:
  port: 8081

spring:
  application:
    name: stay-service

  datasource:
    url: jdbc:postgresql://localhost:5433/${STAY_SERVICE_DB}
    username: ${STAY_SERVICE_DB_USER}
    password: ${STAY_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    "[com.woofwoof.stayservice]": DEBUG
    "[org.springframework.security.oauth2.core]": DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://stayservice-db:5432/${STAY_SERVICE_DB}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
