spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
        - id: stay-service
          uri: lb://stay-service
          predicates:
            - Path=/stays/**
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/medias/**

server:
  port: 8080

eureka:
  instance:
    hostname: api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
